name       : pacman
version    : 0.9.4
release    : 5
source     :
    - git|https://github.com/ebuc99/pacman.git : 03b5cf7568ffaa385cda89f8fb783b91eae2c7bf
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Clone of the original pacman from Namco
description: |
    Pacman is a clone of the original pacman from Namco
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
setup      : |
    %patch -p1 < $pkgfiles/0001-update-desktop-entry.patch
    sed -i "s/\/local//" src/platform.cpp
    %reconfigure --datarootdir=/usr/share/pacman
build      : |
    %make
install    : |
    %make_install
