name       : pacman
version    : 0.9
release    : 1
source     :
    - https://github.com/ebuc99/pacman/archive/v0.9.tar.gz : e0a8fd6d9919b16a539e06c7d3c12bc1bfd41f867366bf8dad72b49f37f8422b
license    : GPL-3.0
component  : games.arcade
summary    : pacman - this is a clone of the original pacman from Namco
description: |
    pacman - his is a clone of the original pacman from Namco
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
setup      : |
    sed -i "s/\/local//" pacman.desktop
    sed -i "s/\/local//" src/platform.cpp
    %configure --datarootdir=/usr/share/pacman
build      : |
    %make
install    : |
    %make_install
